### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by wislem** [esbenp/lumen-api-oauth#1]
Hey Esben, great article!

I faced an issue after grabbing your code.

Pressing the Login button gave me the error below.

```
ParseException in Response.php line 148:
Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON

in Response.php line 148
at Response->json() in Proxy.php line 44
at Proxy->proxy('password', array('username' => 'user@user.com', 'password' => '1234')) in Proxy.php line 11
at Proxy->attemptLogin(array('username' => 'user@user.com', 'password' => '1234')) in routes.php line 20
....
```

**Comment by esbenp** [comment]
Hey Peter. Thanks, glad you liked it!

This is probably because you forgot to run all the migrations and seed the users table (both the oauth2-server-laravel ones and the ones for the user table).

Try running this.

``` bash
php artisan migrate --path=vendor/lucadegasperi/oauth2-server-laravel/migrations && 
php artisan migrate && php artisan db:seed
```

Don't forget to add the Config alias to `bootstrap/app.php` before doing so.

``` php
// It is recommended to remove ALL these lines after the migrations have run.
class_alias('Illuminate\Support\Facades\Config', 'Config');
$app->withFacades();
```

... and you should probably also remove it again :-)

**Comment by jonaholsson** [comment]
Just out of curiosity, why do you recommend Facades to be turned off? I find it very convenient to use e.g. `Auth::` instead of `app('auth')`, but maybe I'm missing the bigger picture?

**Comment by esbenp** [comment]
As far as I have understood the reason why facades are turned off by default in Lumen is that they are very performance intensive. Therefore to keep the implementation in "the Lumen spirit" I recommend turning them off. However, the functionality is still there, so feel free to enable them. There is no right from wrong :-)

**Comment by jonaholsson** [comment]
Fair enough. I just ran some tests on my common routes, and hit an average response time of 170 ms using facades and 165 ms without. Couldn't see much difference in CPU, but on larger solutions I guess it might be more visible :)

**Comment by esbenp** [comment]
Interesting. How many facade calls during the tests?

**Comment by sparkidea** [comment]
Hi

I used the code as you are have placed on Github. But I am getting 500 internal server error whenver i hit Login page.

Am i doing something wrong?

Thanks in advance!

**Comment by esbenp** [comment]
@sparkidea https://github.com/esbenp/lumen-api-oauth/issues/4#issuecomment-109565095

**Comment by sparkidea** [comment]
@esbenp  Yea! I did the same, each and every step that you wrote in this tutorial.

**Comment by ghost** [comment]
Hi Esben, thanks for your post. Exactly what I was looking for.
I am however also having an issue in this regard.

I added the following just after the **try\catch** in `App\Auth\Proxy::proxy()`:

 `app()->make('log')->info($guzzleResponse->getBody());`

This logs the `GuzzleHttp\Exception\BadResponseException` as an html string . The error (extracted from the html) states:

```
The following error was encountered while trying to retrieve the URL: http://localhost:8000/oauth/access-token

The system returned: (101) Network is unreachable

The remote host or network may be down. Please try the request again.

```

The reason for the malformed json error, at least in my case, is because an error is returned in the form of html.

What I can't figure out is why Guzzle is telling me that it can't retrieve the url. I used Postman to test the `'oauth/access-token'` route directly and it works perfectly fine.

I am serving the app using `php artisan serve` and I followed all your instructions from beginning to end.

I don't know, maybe I'm just missing something...

**Comment by esbenp** [comment]
Hey @Cloud5Ideas .

I cannot really tell what your problem is here. Try searching the web for help in regards to using `php artisan serve` and Guzzle together maybe that will find something.
