### ISSUE TITLE
Warning: Ambiguous class resolution, "DatabaseSeeder" ...

### ISSUE THREAD

**Issue by LarryEitel** [esbenp/lumen-api-oauth#12]
Get this when I composer install or run dump_auto.

I can run db:seed with -path=your path
Then I have to do the same for the project seed files.

This becomes a bummer when you wanna migrate:refresh --seed

```
Warning: Ambiguous class resolution, "DatabaseSeeder" was found in both "$baseDir . 
'/database/seeds/DatabaseSeeder.php" and 
"/home/vagrant/Code/xchg/_lumen/vendor/lucadegasperi/oauth2-server-
laravel/seeds/DatabaseSeeder.php", the first will be used.
```

**Comment by jgardezi** [comment]
I having the same issue as well and also this has been fixed for Laravel. Can someone please fix this issue there as well.

Laravel issue link.
https://github.com/lucadegasperi/oauth2-server-laravel/commit/b572ab6b4f952f0a963c4ce086540d98e04cdefe

**Comment by esbenp** [comment]
Seems this has been fixed in https://github.com/lucadegasperi/oauth2-server-laravel/commit/b572ab6b4f952f0a963c4ce086540d98e04cdefe as @jgardezi mentions.

Besides that, Lumen is not particularly good with vendor files. Libraries like https://github.com/irazasyed/larasupport might be able to support you in this, however it is not something I have played around with personally.
